version: "3.8"

services:
  web:
    build: .
    restart: unless-stopped
    command: gunicorn myblog.wsgi:application --bind 0.0.0.0:8000 --workers 3 --timeout 120
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
      - sqlite_data:/app/myblog
    expose:
      - 8000
    environment:
      - DEBUG=0
      - DJANGO_ALLOWED_HOSTS=joeshimbi.tech,www.joeshimbi.tech
      - SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_SETTINGS_MODULE=myblog.settings
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  nginx:
    image: nginx:1.21-alpine
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/app/static
      - media_volume:/app/media
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  sqlite_data:
    name: myblog_sqlite_data
  static_volume:
    name: myblog_static
  media_volume:
    name: myblog_media

networks:
  default:
    name: myblog_network
